---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-write-workload-generator-pv-claim-no-cache
  labels:
    app: cephfs-write-workload-generator-no-cache
spec:
  storageClassName: ocs-external-storagecluster-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
