---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-read-workload-generator-pv-claim-no-cache
  labels:
    app: cephfs-read-workload-generator-no-cache
    dr: active
spec:
  storageClassName: ocs-external-storagecluster-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
